export const DUMMY_ENTRIES_RESPONSE = {
    ok: "true",
    data: {
        previous_page_token: 1724885860.884,
        next_page_token: 1724886282.236,
        entries: [
            {
                activity_count: 1,
                category: "avance_metas",
                created_at: "2024-08-28T16:57:40.884-06:00",
                moderation: "accepted",
                points: 0,
                state: "excuted",
                id: "66cfab6476e9ff8b2f0a1382",
                slug: "avance_metas",
                name: "External",
                participant: {
                    name: "Andrés Hortua",
                    id: "66bf76ff3517509a3b22a645",
                    uid: "12222222",
                    email: "andreshortua@superlikers.com"
                },
                as_form: false,
                data: {}
            },
            {
                activity_count: 1,
                category: "avance_metas",
                created_at: "2024-08-28T17:00:04.293-06:00",
                moderation: "accepted",
                points: 0,
                state: "excuted",
                id: "66cfabf476e9ff8b2f0a1386",
                slug: "avance_metas",
                name: "External",
                participant: {
                    name: "Andrés Hortua",
                    id: "66bf76ff3517509a3b22a645",
                    uid: "12222222",
                    email: "andreshortua@superlikers.com"
                },
                as_form: false,
                data: {}
            },
            {
                activity_count: 1,
                category: "avances_meta",
                created_at: "2024-08-28T17:01:10.619-06:00",
                moderation: "accepted",
                points: 0,
                state: "excuted",
                id: "66cfac3676e9ff8b2f0a1389",
                slug: "avance_metas",
                name: "External",
                participant: {
                    name: "Andrés Hortua",
                    id: "66bf76ff3517509a3b22a645",
                    uid: "12222222",
                    email: "andreshortua@superlikers.com"
                },
                as_form: false,
                data: {
                    volumen_meta_mes_cartones: "907.150206"
                }
            },
            {
                activity_count: 1,
                category: "avance_metas",
                created_at: "2024-08-28T17:01:51.417-06:00",
                moderation: "accepted",
                points: 0,
                state: "excuted",
                id: "66cfac5f76e9ff8b2f0a138c",
                slug: "avance_metas",
                name: "External",
                participant: {
                    name: "Andrés Hortua",
                    id: "66bf76ff3517509a3b22a645",
                    uid: "12222222",
                    email: "andreshortua@superlikers.com"
                },
                as_form: false,
                data: {
                    volumen_meta_mes_hectolitros: "1"
                }
            },
            {
                activity_count: 1,
                category: "avance_metas",
                created_at: "2024-08-28T17:04:42.236-06:00",
                moderation: "accepted",
                points: 0,
                state: "excuted",
                id: "66cfad0a76e9ff8b2f0a138f",
                slug: "avance_metas",
                name: "External",
                participant: {
                    name: "Andrés Hortua",
                    id: "66bf76ff3517509a3b22a645",
                    uid: "12222222",
                    email: "andreshortua@superlikers.com"
                },
                as_form: false,
                data: {
                    volumen_meta_mes_hectolitros: "72.572016",
                    volumen_meta_mes_cartones: "907.150206",
                    volumen_avance_actual_hectolitros: "49.79",
                    volumen_avance_actual_cartones: "558.0",
                    premium_meta_mes_hectolitros: "266.1234",
                    premium_meta_mes_cartones: "557.234",
                    premium_avance_actual_hectolitros: "12.98",
                    premium_avance_actual_cartones: "116.6",
                    innovaciones_meta_mes_hectolitros: "192.67865",
                    innovaciones_meta_mes_cartones: "897.121",
                    innovaciones_avance_actual_hectolitros: "178.2",
                    innovaciones_avance_actual_cartones: "765.1",
                    volumen_el_dorado_avance_actual_hectolitros: "0",
                    volumen_el_dorado_avance_actual_cartones: "0",
                    above_core_avance_actual_cartones: "0",
                    above_core_avance_actual_hectolitros: "0",
                    premium_el_dorado_meta_mes_cartones: "0",
                    premium_el_dorado_avance_actual_cartones: "0",
                    premium_el_dorado_meta_mes_hectolitros: "0",
                    premium_el_dorado_avance_actual_hectolitros: "0",
                    beyond_beer_meta_mes_hectolitros: "12313.1231",
                    beyond_beer_meta_mes_cartones: "12322.11",
                    beyond_beer_avance_actual_hectolitros: "11223.1",
                    beyond_beer_avance_actual_cartones: "1122.1",
                    portafolio_foco_meta_mes_cartones: "0",
                    portafolio_foco_avance_actual_cartones: "0",
                    volumen_sku_meta: "0",
                    volumen_sku_avance: "15",
                    premium_sku_meta: "0",
                    premium_sku_avance: "0",
                    innovaciones_sku_meta: "0",
                    innovaciones_sku_avance: "0",
                    beyond_beer_sku_meta: "0",
                    miscelanea_meta: "0",
                    total_skus_avance_actual_hectolitros: "87",
                    volumen_retornable_meta_mes_cartones: "0",
                    volumen_retornable_meta_mes_hectolitros: "0",
                    volumen_retornable_avance_actual_hectolitros: "0",
                    volumen_retornable_avance_actual_cartones: "0",
                    volumen_retornable_el_dorado_avance_actual_cartones: "0",
                    volumen_retornable_el_dorado_avance_actual_hectolitros: "0",
                    volumen_sellin_meta_mes_hectolitros: "0",
                    volumen_sellin_avance_actual_hectolitros: "0",
                    volumen_sellout_meta_mes_hectolitros: "0",
                    volumen_sellout_avance_actual_hectolitros: "0",
                    volumen_retornable_sellin_meta_mes_hectolitros: "0",
                    volumen_retornable_sellin_avance_actual_hectolitros: "0",
                    marketplace_avance: "30",
                    marketplace_meta: "0",
                    sku_apertura_meta_mes_cartones: "0",
                    sku_cerveza_meta_mes_hectolitros: "0",
                    market_place_pesos_meta: "0",
                    loalty_meta_mes: "0",
                    tdc_meta_mes: "0",
                    volumen_he_meta_mes_hectolitros: "0",
                    volumen_he_meta_mes_cartones: "0",
                    sell_out_total_tickets: "1542",
                    sell_out_total_volume_sell_out: "69.14",
                    sell_out_total_sales_amount_sell_out: "278700.32",
                    sell_out_credit_card_tickets: "12",
                    sell_out_credit_card_volume_sell_out: "0.34",
                    sell_out_credit_card_sales_amount_sell_out: "1315",
                    sell_out_cash_tickets: "1530",
                    sell_out_cash_volume_sell_out: "69.27",
                    sell_out_cash_sales_amount_sell_out: "277385.32",
                    sell_out_transaction_points: "0",
                    portafolio_meta_mes_skus: "0",
                    portafolio_avance_actual_skus: "0",
                    loyalty_avance_loalty_actual_mes: "0",
                    volumen_michelob_avance_mes: "7.640000000000001",
                    volumen_premium_meta_mes_hectolitros: "1.32673",
                    volumen_premium_meta_mes_cartones: "16.584125",
                    volumen_innovaciones_meta_mes_hectolitros: "11.299549",
                    volumen_innovaciones_meta_mes_cartones: "141.244361"
                }
            }
        ]
    }
};
